/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author fabriciogmc
 */
@SuppressWarnings("serial")
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
	private String nome_arq_dados_c;
    public TelaPrincipal(String nome_arq_dados_c) {
    	this.nome_arq_dados_c = nome_arq_dados_c;
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscarContato = new javax.swing.JButton();
        jButtonBuscarContato.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new TelaBusca(nome_arq_dados_c).pack();
        	}
        });
        jLabel1 = new javax.swing.JLabel();
        jButtonListarContatos = new javax.swing.JButton();
        jButtonListarContatos.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		TelaListagem t = new TelaListagem(nome_arq_dados_c);
        		t.setBusca();
        	}
        });
        jButtonCriarContatos = new javax.swing.JButton();
        jButtonCriarContatos.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		new TelaCadastro(nome_arq_dados_c).pack();
        	}
        });

        jButtonBuscarContato.setText("Buscar Contato");

        jLabel1.setText("Operaçoes básicas da agenda de contatos.");

        jButtonListarContatos.setText("Listar Contatos");

        jButtonCriarContatos.setText("Criar Contatos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(176, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addGap(58))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(114)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jButtonListarContatos, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButtonBuscarContato, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButtonCriarContatos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(38)
        			.addComponent(jButtonBuscarContato)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButtonListarContatos)
        			.addGap(18)
        			.addComponent(jButtonCriarContatos)
        			.addContainerGap(112, Short.MAX_VALUE))
        );
        this.getContentPane().setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarContato;
    private javax.swing.JButton jButtonListarContatos;
    private javax.swing.JButton jButtonCriarContatos;
    private javax.swing.JLabel jLabel1;
}
