/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;

import model.ServicoUsuarioImpl;

/**
 *
 * @author fabriciogmc
 */
@SuppressWarnings("serial")
public class TelaCadastroUsuarioAgenda extends javax.swing.JFrame {

	/**
	 * Creates new form TelaCadastroUsuarioAgenda
	 */
	ServicoUsuarioImpl servicoUsuario;
	String nome_arq_dados_u;

	public TelaCadastroUsuarioAgenda(String nome_arq_dados_u) {
		this.nome_arq_dados_u = nome_arq_dados_u;
		servicoUsuario = new ServicoUsuarioImpl();
		initComponents();
		setVisible(true);
		this.setLocationRelativeTo(null);
		setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jButton1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (servicoUsuario.inserir(getjTextFieldNome().getText(), jTextFieldSenha.getText(),
						jTextFieldConfirmSenha.getText(), null) != null) {
					dispose();
				} else {
					JOptionPane.showMessageDialog(null,
							"Atenção aos padrões de cadastro!");
				}
			}

		});
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldNome = new javax.swing.JTextField();
		jTextFieldConfirmSenha = new javax.swing.JTextField();
		jTextFieldSenha = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("Cadastrar");

		jLabel1.setText("Nome de Usuário: ");

		jLabel2.setText("Senha:");

		jLabel3.setText("Confirmaçao de Senha:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(54, 54, 54)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
														116, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
												.createSequentialGroup().addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(getjTextFieldNome(), javax.swing.GroupLayout.PREFERRED_SIZE,
														116, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												layout.createSequentialGroup().addComponent(jLabel3).addGap(49, 49, 49)
														.addComponent(jTextFieldConfirmSenha,
																javax.swing.GroupLayout.PREFERRED_SIZE, 116,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(46, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(26, 26, 26)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(getjTextFieldNome(),
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2).addComponent(jTextFieldSenha,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jTextFieldConfirmSenha,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton1)
						.addContainerGap(28, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public javax.swing.JTextField getjTextFieldNome() {
		return jTextFieldNome;
	}

	public javax.swing.JTextField getjTextFieldConfirmSenha() {
		return jTextFieldConfirmSenha;
	}

	public javax.swing.JTextField getjTextFieldSenha() {
		return jTextFieldSenha;
	}



	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JButton jButton1;
	public javax.swing.JLabel jLabel1;
	public javax.swing.JLabel jLabel2;
	public javax.swing.JLabel jLabel3;
	public javax.swing.JTextField jTextFieldNome;
	public javax.swing.JTextField jTextFieldConfirmSenha;
	public javax.swing.JTextField jTextFieldSenha;
	// End of variables declaration//GEN-END:variables
}
