/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;

import model.Contato;
import model.ServicoContatoImpl;

/**
 *
 * @author fabriciogmc
 */
@SuppressWarnings("serial")
public class TelaCadastro extends javax.swing.JFrame {

	/**
	 * Creates new form TelaCadastro
	 */

	private ServicoContatoImpl servicoContato;
	private Contato cAnt = null;

	public TelaCadastro(String nome_arq_dados_c) {
		servicoContato = new ServicoContatoImpl(nome_arq_dados_c);
		initComponents();
		setLocationRelativeTo(null);
		setVisible(true);
	}

	public void editarContato(Contato cAnt) {
		this.cAnt = cAnt;
		jTextFieldNome.setText(cAnt.getNome());
		jTextFieldTelefone.setText(cAnt.getTelefone());
		jTextFieldEmail.setText(cAnt.getEmail());
		jTextFieldEndereco.setText(cAnt.getEndereco());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTextFieldNome = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldEndereco = new javax.swing.JTextField();
		jTextFieldTelefone = new javax.swing.JTextField();
		jTextFieldEmail = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				Contato c = new Contato();
				c.setNome(jTextFieldNome.getText());
				c.setTelefone(jTextFieldTelefone.getText());
				c.setEmail(jTextFieldEmail.getText());
				c.setEndereco(jTextFieldEndereco.getText());

				if (cAnt != null) {
					Contato cAtual = new Contato();
					cAtual.setNome(jTextFieldNome.getText());
					cAtual.setTelefone(jTextFieldTelefone.getText());
					cAtual.setEmail(jTextFieldEmail.getText());
					cAtual.setEndereco(jTextFieldEndereco.getText());
					servicoContato.atualizarContato(cAnt, cAtual);
					
					JOptionPane.showMessageDialog(null, "Usuário Cadastrado com sucesso");
					dispose();
 				}
				
				else {
					if (servicoContato.inserir(jTextFieldNome.getText(), jTextFieldTelefone.getText(),
							jTextFieldEmail.getText(), jTextFieldEndereco.getText()) != null) {
						JOptionPane.showMessageDialog(null, "Usuário Cadastrado com sucesso");
						dispose();
					} else {
						JOptionPane.showMessageDialog(null, "Atençao as regras de cadastro");
					}
				}
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Nome");

		jLabel2.setText("Telefone");

		jLabel3.setText("Email");

		jLabel4.setText("Endereço");

		jButton1.setText("Cadastrar");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(32, 32, 32)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1).addComponent(jLabel3).addComponent(jLabel2))
								.addGap(21, 21, 21)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 211,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 211,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup().addComponent(jLabel4).addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jTextFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 211,
												Short.MAX_VALUE))))
				.addContainerGap(55, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(42, 42, 42)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel1))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
								.addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(jTextFieldEmail,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18).addComponent(jLabel4))
						.addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addComponent(jButton1).addContainerGap(79, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField jTextFieldNome;
	private javax.swing.JTextField jTextFieldEndereco;
	private javax.swing.JTextField jTextFieldTelefone;
	private javax.swing.JTextField jTextFieldEmail;
	// End of variables declaration//GEN-END:variables
}
